name: Compile binaries

# For production
# on:
#   release:
#     types: [published]


# For testing
on: 
  push:
    branches:
      - master


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: install deps
         run: sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev zip
       - name: build
         run: mkdir build && cd build && cmake .. && make
       - name: zip 
         run: cd build && mkdir kryptokrona-xmrig-${{ github.event.head_commit.message }}-linux && mv xmrig kryptokrona-xmrig-${{ github.event.head_commit.message }}-linux && zip -r kryptokrona-xmrig-${{ github.event.head_commit.message }}-linux kryptokrona-xmrig-${{ github.event.head_commit.message }}-linux
       - name: Release
         uses: softprops/action-gh-release@v1
         if: startsWith(${{ github.event.head_commit.message }}, 'v*)
         with:
          files: kryptokrona-xmrig-${{ github.event.head_commit.message }}-linux.zip
