name: Compile binaries

# For production
# on:
#   release:
#     types: [published]


# For testing
on: push


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: install deps
         run: sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev zip
       - name: build
         run: mkdir build && cd build && cmake .. && make
       - name: zip 
         run: ls -l && mkdir kryptokrona-xmrig-${GITHUB_REF#refs/*/}-linux && mv xmrig kryptokrona-xmrig-${GITHUB_REF#refs/*/}-linux && zip -r kryptokrona-xmrig-${GITHUB_REF#refs/*/}-linux kryptokrona-xmrig-${GITHUB_REF#refs/*/}-linux
       - name: Release
         uses: softprops/action-gh-release@v1
         if: startsWith(github.ref, 'refs/tags/')
         with:
          files: kryptokrona-xmrig-${GITHUB_REF#refs/*/}-linux.zip
